### ISSUE TITLE
any chance of a homebrew formula?

### ISSUE THREAD

**Issue by rhaynes74** [phillmv/arquivo#28]
Good day - I am interested in trying out your tool, for some reason I am getting errors during the install with various ruby packages.   Any chance of putting together a homebrew package?

**Comment by phillmv** [comment]
> Good day - I am interested in trying out your tool, for some reason I am getting errors during the install with various ruby packages. Any chance of putting together a homebrew package?

I would like to _avoid the extra work_ since I don't think that's how I'll end up distributing it in the future, but I am happy to give you a hand! The app as it is is not yet friendly to outsiders, and there's likely a few broken bits. I went ahead and added some more information in the README: https://github.com/phillmv/arquivo/blob/master/README.md

If you're on homebrew, the Ruby packages at least should be relatively easy.

Would you care to share your ruby version, osx version, and any errors you've been experiencing :)?

**Comment by rhaynes74** [comment]
Hi - thanks for the reply.  Understood.  I am running Big Sur 11.4, here is the output from bundle where the error occurs:

Using rails 6.0.2.1
Using octicons_helper 9.4.0
Using pry 0.12.2
Using pry-rails 0.3.9
Installing puma 4.3.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

 current directory: /Library/Ruby/Gems/2.6.0/gems/puma-4.3.5/ext/puma_http11
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r
./siteconf20210608-73054-13mozjz.rb extconf.rb
checking for BIO_read() in -lcrypto... no
checking for BIO_read() in -llibeay32... no
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/puma-4.3.5/ext/puma_http11
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/puma-4.3.5/ext/puma_http11
make "DESTDIR="
compiling http11_parser.c
compiling io_buffer.c
compiling mini_ssl.c
compiling puma_http11.c
puma_http11.c:203:22: error: implicitly declaring library function 'isspace' with type 'int (int)'
[-Werror,-Wimplicit-function-declaration]
 while (vlen > 0 && isspace(value[vlen - 1])) vlen--;
 ^
puma_http11.c:203:22: note: include the header <ctype.h> or explicitly provide a declaration for
'isspace'
1 error generated.
make: *** [puma_http11.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/puma-4.3.5 for inspection.
Results logged to
/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/puma-4.3.5/gem_make.out

An error occurred while installing puma (4.3.5), and Bundler cannot continue.
Make sure that `gem install puma -v '4.3.5' --source 'https://rubygems.org/'` succeeds before
bundling.

In Gemfile:
 puma

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by phillmv** [comment]
Looks like Apple changed [some libraries around](https://github.com/puma/puma/issues/2304#issuecomment-664448309).

According to that link, can you try running:

 ```
gem install puma:4.3.5 -- --with-cflags="-Wno-error=implicit-function-declaration"
```

This should get the local C extension built, and then you can run `bundle install` again.

If that doesn't work, I can try upgrading the gem to version 5 😄.

**Comment by rhaynes74** [comment]
Thanks for the suggestion - the forced install of puma worked;

gem install puma:4.3.5 -- --with-cflags="-Wno-error=implicit-function-declaration"
Building native extensions with: '--with-cflags=-Wno-error=implicit-function-declaration'
This could take a while...
Successfully installed puma-4.3.5
Parsing documentation for puma-4.3.5
Done installing documentation for puma after 0 seconds
1 gem installed

But then bundle gave the same error:

puma_http11.c:203:22: error: implicitly declaring library function 'isspace' with type 'int (int)'
[-Werror,-Wimplicit-function-declaration]
 while (vlen > 0 && isspace(value[vlen - 1])) vlen--;
 ^
puma_http11.c:203:22: note: include the header <ctype.h> or explicitly provide a declaration for
'isspace'
1 error generated.
make: *** [puma_http11.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/var/folders/mp/v5g4ph213_g7ymvvf2l4yk_h0000gr/T/bundler20210608-78239-xj6ymipuma-4.3.5/gems/puma-4.3.5
for inspection.
Results logged to
/var/folders/mp/v5g4ph213_g7ymvvf2l4yk_h0000gr/T/bundler20210608-78239-xj6ymipuma-4.3.5/extensions/universal-darwin-20/2.6.0/puma-4.3.5/gem_make.out

An error occurred while installing puma (4.3.5), and Bundler cannot continue.
Make sure that `gem install puma -v '4.3.5' --source 'https://rubygems.org/'` succeeds before
bundling.

In Gemfile:
 puma

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by phillmv** [comment]
Hrm, looks like it's trying to re-compile Puma, which is annoying - it should have picked up the version you just compiled. What if you pass the config directly to bundler, i.e.

```
bundle config build.puma --with-cflags="-Wno-error=implicit-function-declaration"
```

and try again?

If that fails I can try upgrading Puma.

**Comment by rhaynes74** [comment]
Ok - that got me further!  But yarn install threw errors!

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:131:2: error: unknown type name 'uint32_t'
 uint32_t n_net; /* network # */
 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:280:29: error: unknown type name 'uint32_t'
struct netent *getnetbyaddr(uint32_t, int);
 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/Cellar/node/16.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (node:events:394:28)
gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command \"/usr/local/Cellar/node/16.3.0/bin/node\" \"/usr/local/Cellar/node/16.3.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/rhaynes/GitProjects/arquivo/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v16.3.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error

And although it says I can safely ignore this error, when I run:

bundle exec rails db:setup

I get:

========================================
 Your Yarn packages are out of date!
 Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by phillmv** [comment]
That's bizarre! That smells like something funny going on in your build environment.

FWIW, I've never been able to get fsevents to work properly either. What happens if you tell webpacker to ignore the integrity?

>To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).

i.e. edit the `config/webpacker.yml` file and change the `check_yarn_integrity` key to `false`.

---

Sorry you're experiencing this pain; this is all very valuable feedback - I need to update some gems, figure out why node is such a pain, and maybe just ship a docker image for development. I myself came across the integrity error last night for the first time.

**Comment by rhaynes74** [comment]
Hi - thanks again for your assistance, setting the flag to false helped! Was able to create the databases but the final step
bundle exec rails c


gives

/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (1.17.2) required by `$BUNDLER_VERSION`. (Gem::MissingSpecVersionError)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
Checked in 'GEM_PATH=/Library/Ruby/Gems/2.6.0:/Users/rhaynes/.gem/ruby/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0' , execute `gem env` for more information
	from /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
	from <internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:73:in `require'

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by phillmv** [comment]
That's because I used an ancient version of bundler 😅, tho strange if `bundle exec rails db:setup` / `bundle install` worked; it should've given you this error then too!

Try `gem install bundler:1.17.2` and see how that goes. I believe bundler can co-exist with multiple versions of itself.

**Comment by rhaynes74** [comment]
Do you happen to have a screencast of a typical workflow with the tool? Would be good to know if I want to continue to fight through the install at this point! :-)

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by phillmv** [comment]
hah, cheers Ronald, thanks for getting this far. I do not at the moment, because 90% of the work I use it for can't be shown publicly, and it remains an experimental tool.

You can get a sense of some of its capabilities via this static site export: https://phillmv.github.io/public/ which generates about 70% of the functionality (i.e. no full text search, no todo lists).

If you'd like, I can ping you whenever I get around to making a hosted version.

If you don't mind me asking, how did you come across this in the first place?

Cheers,

**Comment by rhaynes74** [comment]
Yes - please keep me abreast.  I have recently been looking for effective workflow options for academic writing and literature notetaking.

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
